### ISSUE TITLE
Gallery not working with the npm package import

### ISSUE THREAD

**Issue by Aminerman** [peremp/vue-light-gallery#4]
Hello,

Thank you for the good work. I managed to make your component work by extending it directly from the src directory from node_modules. And it fits what I need, as it's simple but functional.
But when I try to use it the regular way : 

```javascript
import LightGallery from "vue-light-gallery";

export default {
  data() {
    return {
      images: [
        { title: "img 1", url: "https://picsum.photos/1200/800?image=1024" },
        { title: "img 2", url: "https://picsum.photos/1000/1000?image=935" },
        { title: "img 3", url: "https://picsum.photos/800/1200?image=1003" },
        { title: "img 4", url: "https://picsum.photos/1200/800?image=937" }
      ],
      index: null
    };
  },
  components: {
    LightGallery
  }
};
```

it throws this error : 

![Capture d’écran 2019-03-19 à 17 43 05](https://user-images.githubusercontent.com/7825144/54625258-35720180-4a6f-11e9-8db2-1073a4a0966b.png)

Where could it be coming from?

**Comment by peremp** [comment]
You should add this after the import:

`Vue.use(LightGallery);`

**Comment by Aminerman** [comment]
It does work now, Thank you. 

But it's a rather unusual pattern if I want to use the gallery inside another component, as I'm not willing to add it to my main Vue instance. It'd be better to be able to import it as a component. What do you think?

**Comment by peremp** [comment]
You can also do this:
```
import { LightGallery } from 'vue-light-gallery';
```

and then:

```
components: {
    LightGallery
}
```

**Comment by Aminerman** [comment]
Oh my... true story. Thanks a bunch!

**Comment by peremp** [comment]
no problem :-)

P.D: Closing the issue
