### ISSUE TITLE
only one image

### ISSUE THREAD

**Issue by empdigitalcl** [peremp/vue-light-gallery#5]
Hi, this not work only one image on array? like this:

images: [
 { title:'img 1', url: 'path/to/image_1.jpg' },
],

**Comment by peremp** [comment]
Yes, it works.
Are you having issues?

**Comment by empdigitalcl** [comment]
Yeah, show the loading view, when put  the array whit more one image works

**Comment by peremp** [comment]
It's working fine.
Here a working example: https://codepen.io/peremp/pen/mYVOZm

**Comment by peremp** [comment]
since it cannot be reproduced and looks like it works properly I close the issue.
